Modify SSE config for server
modelcontextprotocol/kotlin-sdk pull request #23
Opened 2024-12-18 15:00 UTC by Mr3zee

Modify SSE config for server:
- rename to Kotlin style guide
- remove NPE
- manage paths clearly

UPD: Additionally fixes compilation in master and hanged tests

2024-12-18 17:27 UTC, e5l requested changes

2024-12-18 17:27 UTC, e5l commented on src/main/kotlin/io/modelcontextprotocol/kotlin/sdk/server/McpKtorServerPlugin.kt
> +public fun Routing.mcp(block: () -> Server) {
Please keep old extension for compatibility

2024-12-18 17:27 UTC, e5l commented on src/main/kotlin/io/modelcontextprotocol/kotlin/sdk/server/McpKtorServerPlugin.kt
> -    install(SSE)
Please keep SSE to have configuration simple

2024-12-18 17:27 UTC, e5l commented on src/main/kotlin/io/modelcontextprotocol/kotlin/sdk/server/McpKtorServerPlugin.kt
> +    application.install(SSE)
Could you tell me what is the purpose of the plugin?

2025-01-20 18:14 UTC, Mr3zee commented
To be merged after #37

2025-01-22 11:46 UTC, e5l approved these changes

2025-01-24 12:31 UTC, merged